### PR TITLE
Updates to Navigation and Implementation of Fixed Navigation

### PR DESCRIPTION
**Pull request by whoiskenjackson**
Features Added:

- Fixed Navigation. See the Navigation Demo. Not sure how you wanted to display this so I just created another page to showcase how it works. The functionality will always be there, so feel free to delete the page if you want.

Updates:

- Cleaned up the CSS a bit. I through a lot of crappy code on top of the navigation stuff originally. So I went back and cleaned it all up.

- Renamed some of the CSS Classes to only be one words.

- Updated the JS for the dropdowns on mobile.

### CODE REVIEW

**Comment by kurisubrooks** [comment]
— Navbar dropdowns are broken
— Button dropdowns are broken
— Pagination is broken
(Because you changed the code, remember to update the index.html)

— Why'd you move the button dropdowns in index.html?
— Why'd you make the front-end more complicated aswell, the point of Caramel is to be simple. Unlike bootstrap.

Also, try not to change the element and class names once they've been set, so people's works don't break.

+ On the other hand, the new Fixed Nav looks great, but the front-end is too complicated.

**Comment by kurisubrooks** [comment]
Hop on IRC ~

**Comment by kurisubrooks** [comment]
When collapsed, the Sign In and Sign Up buttons for some reason get placed backwards.
Also, **get on IRC** please :smile:

**Comment by whoiskenjackson** [comment]
Yep,

Well that's just how floats work. If you look at the markup, they are naturally laid out in the opposite order that they appear on desktop. So when you go to mobile, you get the natural order. I'll add in the ability to add in another UL inside of the navigation that you can float right. But if a user ever adds the floats to the li's, that's on them and we can't fix that.

**Pull request closed without merging**
