### PR TITLE
Button Dropdown

### PR DESCRIPTION
**Pull request by whoiskenjackson**
Second attempt at Button Dropdown.

- Removed class-name btn-dropdown. Though in the future we should consider something along the lines of: https://smacss.com/ for our naming conventions. Eventually we'll run out of one word class names.

- Removed extra Javascript and fine tuned. The navigation will still have to use JS, but we can avoid it for the button dropdowns for now. However, if we want to use some of the other variations that are in Bootstrap, we may need to revert back to the old way.

- Refactored some CSS and HTML.

### CODE REVIEW

**Comment by kurisubrooks** [comment]
— For some reason still isn't using the Correct fonts

**Comment by whoiskenjackson** [comment]
Can you send me a screenshot? Nothing with the fonts has changed. I moved the reference to the file but that shouldn't make a difference. I am still getting all of the fonts.

When you open your developer tools and look in the console, are you getting any errors?

**Comment by kurisubrooks** [comment]
— Yours : http://kurisubrooks.com/img/2015-03-11_1525.png
— Mine : http://kurisubrooks.com/img/2015-03-11_1526.png

Even font-awesome isn't loaded.

**Comment by whoiskenjackson** [comment]
Do you think it has something to do with the way you're trying to preview it? It's working locally for me, and I setup a alias in apache to make sure it would work within a "domain" environment.

**Comment by kurisubrooks** [comment]
Maybe an OS difference? It worked before when I specified it to load in Caramel.scss, but never worked when I put it in core.

**Comment by whoiskenjackson** [comment]
Yours: http://htmlpreview.github.io/?https://github.com/kurisubrooks/caramel/blob/dev/src/index.html
Mine: http://htmlpreview.github.io/?https://github.com/whoiskenjackson/caramel/blob/dev/src/index.html

They look the same to me. I can try to load it up on a Windows machine and see if there are any issues.

**Comment by kurisubrooks** [comment]
Now neither are working for me...
Also, i'm on a Mac.

Let me check something.

**Comment by kurisubrooks** [comment]
.. yeah i have no idea

**Comment by whoiskenjackson** [comment]
Oh you're on a Mac? Odd, we should be the same. What browser are you using?

Try downloading my zip file and seeing if it works locally: https://github.com/whoiskenjackson/caramel/archive/dev.zip

Also, side note, I noticed that the preview environment has some console errors. I don't think that would fix the font issue but it will probably fix any JS stuff. I think it's pretty strict about some things. Maybe not the best place to test.

**Comment by kurisubrooks** [comment]
..that's odd, it works fine locally.

**Comment by whoiskenjackson** [comment]
So maybe it's just the preview environment?

**Comment by kurisubrooks** [comment]
Dunno. I'm uploading to FTP so I can see if it works online.

**Comment by kurisubrooks** [comment]
Also, get on IRC. Much easier :smile:

**Comment by whoiskenjackson** [comment]
Oh yes!

**Pull request merged**
